title: StayTime - AppLock Ultimate
description: Protect your privacy and promote healthy phone usage
theme: jekyll-theme-cayman
show_downloads: false
google_analytics: # 如果需要添加 Google Analytics，在这里添加跟踪 ID
github:
  is_project_page: false

# 多语言设置
defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"
  -
    scope:
      path: "zh"
    values:
      lang: "zh"
  -
    scope:
      path: "ru"
    values:
      lang: "ru" 